### ISSUE TITLE
patched

### ISSUE THREAD

**Issue by itschasa** [TEERMIIINAAL/Root-Nuker#5]
you get token banned when you mass ban more than 500+

i made one similar apart from it uses proxies and also doesn't create a thread per id
it uses 50 threads and it still gets banned so i think that its fully patched or something

**Comment by itschasa** [comment]
quick note: ik this tool is designed for bots, not user accounts, but would it make a difference?

**Comment by itschasa** [comment]
im retard

**Comment by TEERMIIINAAL** [comment]
okokok
